### ISSUE TITLE
Archive message action incompatible with Rapidpro

### ISSUE THREAD

**Issue by KaitCrawford** [rapidpro/rapidpro-python#77]
I'm not sure if this is an issue to be addressed in this library or in RapidPro.

The `bulk_archive_contacts` method was changed to the `bulk_archive_contact_messages` method in this commit https://github.com/rapidpro/rapidpro-python/commit/f65979c8e06cef9d4bb1982dee55a17a2d19947b
However the RapidPro Contacts view does not recognise `archive_messages` as an action https://github.com/rapidpro/rapidpro/blob/main/temba/contacts/views.py#L535-L554

Should this action be added to that view or should the method rather point to the message views to archive the contact messages?

**Comment by rowanseymour** [comment]
This API client doesn't touch the RapidPro CRUDL views - `bulk_archive_contact_messages` calls the contact bulk actions API endpoint http://textit.com/api/v2/contact_actions

It used to have an action called just `archive` which would archive the contact's message.. but that got confusing when archiving contacts (status=ARCHIVED) became a thing so we had to rename this action so that one day.. archiving a contact here means archiving the contact rather than its messages.

**Comment by KaitCrawford** [comment]
Ah thank you Rowan!

And I see that change was added in v5.7.24 of RapidPro which explains why we're getting errors when trying to connect to an instance running v5.6.5.
Thank you for clearing that up.
