### ISSUE TITLE
Why get_groups() has no after and before

### ISSUE THREAD

**Issue by xkmato** [rapidpro/rapidpro-python#8]
So I am wondering why some of the TembaClient methods like get_groups don't have after and before kwargs. Is there a specific reason behind that or should I add it?

**Comment by rowanseymour** [comment]
That's because the API endpoint on the rapidpro side doesn't have those params. Ordinarily I would say add them for consistency, but it's likely that rapidpro will have to expose a more limited API in the future for scaling reasons so unless there's an important use case, then I'd leave the endpoints as they are.
